title: "[Show & Tell]:"
labels: ["showcase"]
body:
  - type: markdown
    attributes:
      value: |
        Share how you're using plugin-dev! We'd love to hear about your projects and learnings.

  - type: dropdown
    id: component-type
    attributes:
      label: What type of component?
      options:
        - Complete plugin
        - Skill
        - Agent
        - Hook
        - Command
        - Marketplace
        - Other
    validations:
      required: true

  - type: textarea
    id: showcase
    attributes:
      label: What are you sharing?
      description: Describe what you built or accomplished
      placeholder: I used plugin-dev to...
    validations:
      required: true

  - type: textarea
    id: learnings
    attributes:
      label: Key Learnings
      description: What did you learn that might help others? This is the heart of Show and Tell!
      placeholder: Tips I'd share...
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links or Resources
      description: Any relevant links to your project, blog post, or resources
      placeholder: "GitHub repo: ... Blog post: ..."
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Sharing preferences
      options:
        - label: I'm okay with this being featured in project documentation
          required: false
